name:  Hello Project 🌸

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  soso-job:
    runs-on: ubuntu-latest
    steps:
      - name:  Récupérer le projet
        uses: actions/checkout@v4

      - name:  Lire un message 
        run: cat message.txt

      - name:  Exécuter le script 
        run: |
          chmod +x soso.sh
          ./soso.sh
