name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        run: echo "Bonjour GitHub Actions 👋"

      - name: Afficher la date
        run: date

      - name: Lister les fichiers
        run: ls -la
